AWSTemplateFormatVersion: 2010-09-09

Description: Calls Sub Templates # TODO wait handlers to ensure proper start up

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            - Label:
                default: Creation Configuration
              Parameters:
                - Owner
                - Classification
                - PartitionName

        ParameterLabels:
            AmiId:
                default: AMI Id
            JumpBoxInstanceType:
                default: Instance Type of the Jumpbox
            BastionInstanceType:
                default: Instance Type of the Bastion Host

Parameters:

CreateVPCStack:
      Description: Creation of VPC Child Stack
      Type: String
      Default: true
      AllowedValues:
        - "true"
        - "false"

  AmiId: #EC2
    Default: ami-00936483548a6d57f
    Description: Red Hat Enterprise Linux 7.7 Cloud Access  # Change this for your setup
    Type: AWS::EC2::Image::Id

  JumpBoxInstanceType:
    Default: t3.micro
    Description: Instance type of the Jump Host
    Type: String

  BastionInstanceType:
    Default: t3.micro
    Description: Instance type of the Bastion Host
    Type: String

Mappings:
  ClassificationMap:
      "Unclassified":
        ClassificationText: "UNCLASSIFIED"
        ClassificationScript: unclassified.js
        ClassificationColor: "#5cb85c"
      "Confidential":
        ClassificationText: "CONFIDENTIAL"
        ClassificationScript: confidential.js
        ClassificationColor: "#286090"
      "Secret":
        ClassificationText: "SECRET"
        ClassificationScript: secret.js
        ClassificationColor: "#d9534f"
      "TopSecret":
        ClassificationText: "TOP SECRET"
        ClassificationScript: topsecret.js
        ClassificationColor: "#f0ad4e"

Conditions:
  CreateVPCResources: !Equals [ !Ref CreateVPCStack, true ]



Resources:

#  SecurityGroupStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://${S3ServiceName}/${S3ArtifactsPath}/open-shift/cloudformation/open-shift-security-groups.yml'
#      Parameters:
#        StackName: !Ref AWS::StackName
#        VpcId: !Ref VpcId
#        VpcCIDR: !Ref VpcCIDR

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Condition: CreateVPCResources
    Properties:
      TemplateURL: !Sub 'file://vpc-2azs-legacy.yaml'
      Parameters:
        S3ArtifactsPath: !Sub '${S3ArtifactsPath}'



